In [1]:
import pandas as pd
import numpy as np

## Kolon Adları
- vSegID	Segment bölgesini belirtir
- vSegDir	YÖN: 0:Geliş; 1:Gidiş
- fusedYear	Yıl
- fusedMonth	Ay
- fusedday	Gün
- fusedHour	Saat
- avgspeed	km'saat
- GRP	30'dklık dilimler
- shape	Segment ıdların koordinat bilgileri

### NOT: Elimizde hem Beşiktaş'a özel bir veri(besiktasHız.csv) hem de tüm ilçelerin karışık olduğu bir veri (fuseedİlce.csv) var. Bu sebeple ikisini birleştiriyoruz.

In [2]:
BESIKTAS_DATA = "./BesiktasHiz.csv"
FUSEED_DATA = "./Fuseed_Data_İlçe.csv"

In [3]:
besiktas_df = pd.read_csv(BESIKTAS_DATA, sep=";")

In [4]:
besiktas_df.head()

,vSegID,vSegDir,fusedYear,fusedMonth,fusedday,fusedHour,avgspeed,GRP
0,470,1,2019,3,17,8,108.0,30-60DK
1,3597,0,2019,3,5,8,33.0,30-60DK
2,3639,1,2019,1,2,22,37.0,0-30DK
3,2143,0,2019,3,2,21,30.0,30-60DK
4,551,0,2019,1,12,21,41.0,30-60DK

In [5]:
fuseed_df = pd.read_csv(FUSEED_DATA)

In [6]:
fuseed_df.head()

,vSegID,vSegDir,fusedYear,fusedMonth,fusedday,fusedHour,avgspeed,GRP
0,305,1,2019,6,24,23,28.0,0-30DK
1,1107,1,2019,6,5,2,49.0,30-60DK
2,1728,0,2019,4,15,14,73.0,0-30DK
3,762,0,2019,5,6,10,30.0,0-30DK
4,3023,1,2019,5,4,18,25.0,30-60DK

In [7]:
fuseed_besiktas_df = fuseed_df[fuseed_df.vSegID.isin(besiktas_df.vSegID)]

In [8]:
fuseed_besiktas_df.head()

,vSegID,vSegDir,fusedYear,fusedMonth,fusedday,fusedHour,avgspeed,GRP
1,1107,1,2019,6,5,2,49.0,30-60DK
10,3552,0,2019,6,1,8,28.0,30-60DK
15,3559,0,2019,4,14,20,44.0,30-60DK
24,3589,0,2019,6,10,16,34.0,0-30DK
26,3619,0,2019,4,6,12,37.0,30-60DK

In [9]:
df = besiktas_df.append(fuseed_besiktas_df)

In [10]:
df.head()

,vSegID,vSegDir,fusedYear,fusedMonth,fusedday,fusedHour,avgspeed,GRP
0,470,1,2019,3,17,8,108.0,30-60DK
1,3597,0,2019,3,5,8,33.0,30-60DK
2,3639,1,2019,1,2,22,37.0,0-30DK
3,2143,0,2019,3,2,21,30.0,30-60DK
4,551,0,2019,1,12,21,41.0,30-60DK

## Toplam Satır Sayıları

In [11]:
print(f'Besiktas veriseti: {len(besiktas_df.index)} satır')
print(f'Fuseed verisetindeki Besiktas verisi: {len(fuseed_besiktas_df.index)} satır')
print(f'Toplam Besiktas: {len(df.index)} satır')

Besiktas veriseti: 938941 satır
Fuseed verisetindeki Besiktas verisi: 921576 satır
Toplam Besiktas: 1860517 satır

## Segment ID'lere karşılık gelen enlem boylam verileri

In [12]:
segment_list = pd.read_excel("./bjk-segment.xlsx")

In [13]:
segment_list.head()

   id                                              shape
0  58  LINESTRING ( 29.01163774408752 41.080480711216...
1  58  LINESTRING ( 29.01837697841569 41.088996478005...
2  59  LINESTRING ( 29.01851958661052 41.088856751239...
3  59  LINESTRING ( 29.03193200006262 41.092135999577...
4  62  LINESTRING ( 29.00868344598513 41.050657973587...

## Seçilen Yola Göre Filtreleme

Elimizdeki segment id'lere karşılık gelen enlem-boylam verisinden bir cadde seçip tüm veriyi filtreleyelim.

In [14]:
segment_list.loc[segment_list['id'] == 65]

    id                                              shape
10  65  LINESTRING ( 29.0068330000438 41.0423210001149...
11  65  LINESTRING ( 29.00779224661579 41.047637999794...

In [15]:
test = df.loc[df['vSegID'] == 65]
test2 = test.loc[test['vSegDir'] == 0]
test3 = test2.loc[test2['fusedMonth'] == 6]
test4 = test3.loc[test3['fusedday'] == 1]
test4.sort_values("fusedHour").reset_index(drop=True)

,vSegID,vSegDir,fusedYear,fusedMonth,fusedday,fusedHour,avgspeed,GRP
0,65,0,2019,6,1,0,44.0,30-60DK
1,65,0,2019,6,1,0,46.0,0-30DK
2,65,0,2019,6,1,1,49.0,0-30DK
3,65,0,2019,6,1,1,50.0,30-60DK
4,65,0,2019,6,1,2,51.0,0-30DK
5,65,0,2019,6,1,2,55.0,30-60DK
6,65,0,2019,6,1,3,58.0,0-30DK
7,65,0,2019,6,1,3,58.0,30-60DK
8,65,0,2019,6,1,4,55.0,0-30DK
9,65,0,2019,6,1,4,55.0,30-60DK
10,65,0,2019,6,1,5,62.0,30-60DK
11,65,0,2019,6,1,5,59.0,0-30DK
12,65,0,2019,6,1,6,62.0,0-30DK
13,65,0,2019,6,1,6,59.0,30-60DK
14,65,0,2019,6,1,7,53.0,0-30DK
15,65,0,2019,6,1,7,52.0,30-60DK
16,65,0,2019,6,1,8,31.0,30-60DK
17,65,0,2019,6,1,8,47.0,0-30DK
18,65,0,2019,6,1,9,50.0,0-30DK
19,65,0,2019,6,1,9,47.0,30-60DK
20,65,0,2019,6,1,10,47.0,0-30DK
21,65,0,2019,6,1,10,46.0,30-60DK
22,65,0,2019,6,1,11,42.0,30-60DK
23,65,0,2019,6,1,11,46.0,0-30DK
24,65,0,2019,6,1,12,42.0,30-60DK
25,65,0,2019,6,1,12,42.0,0-30DK
26,65,0,2019,6,1,13,29.0,30-60DK
27,65,0,2019,6,1,13,43.0,0-30DK
28,65,0,2019,6,1,14,31.0,0-30DK
29,65,0,2019,6,1,14,42.0,30-60DK
30,65,0,2019,6,1,15,44.0,0-30DK
31,65,0,2019,6,1,15,46.0,30-60DK
32,65,0,2019,6,1,16,45.0,0-30DK
33,65,0,2019,6,1,16,43.0,30-60DK
34,65,0,2019,6,1,17,43.0,0-30DK
35,65,0,2019,6,1,17,45.0,30-60DK
36,65,0,2019,6,1,18,43.0,0-30DK
37,65,0,2019,6,1,18,42.0,30-60DK
38,65,0,2019,6,1,19,35.0,0-30DK
39,65,0,2019,6,1,19,35.0,30-60DK
40,65,0,2019,6,1,20,48.0,0-30DK
41,65,0,2019,6,1,20,51.0,30-60DK
42,65,0,2019,6,1,21,48.0,0-30DK
43,65,0,2019,6,1,21,43.0,30-60DK
44,65,0,2019,6,1,22,32.0,30-60DK
45,65,0,2019,6,1,22,35.0,0-30DK
46,65,0,2019,6,1,23,27.0,30-60DK
47,65,0,2019,6,1,23,42.0,0-30DK

## Yol Bakım
2 adet bakım calısması veriseti var.

- İki verisetini birleştir.
- Beşiktaş Barbaros Bulvarına göre filtrele.

In [16]:
yol_bakim1 = pd.read_csv("./bakim-veri/yol_bakım.csv")
yol_bakim2 = pd.read_csv("./bakim-veri/yol_bakim_2.csv")

In [17]:
result = pd.concat([yol_bakim1, yol_bakim2])
result = result.loc[result["ilce"] == "BEŞİKTAŞ"].reset_index(drop=True)
result.loc[result['yol_adi'].str.contains("BARBAROS")].reset_index(drop=True)

,id,isin_cinsi,ilce,yol_adi,isin_adi,tarih,gece,harita,lat,lon
0,133679,UTK,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),TRETUVAR - PARKE ÇALIŞMASI,2019-01-05,HAYIR,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,0.000000,0.00000
1,133950,UTK,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),TRETUVAR - PARKE ÇALIŞMASI,2019-01-09,HAYIR,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,0.000000,0.00000
2,134346,UTK,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),TRETUVAR - PARKE ÇALIŞMASI,2019-01-13,HAYIR,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,0.000000,0.00000
3,134579,UTK,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),TRETUVAR - PARKE ÇALIŞMASI,2019-01-14,HAYIR,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,0.000000,0.00000
4,134691,ASFALT,BEŞİKTAŞ,BARBAROS BULVARI(YILDIZ MAH),ROBOT (YAMA),2019-01-15,EVET,http://sehirharitasi.ibb.gov.tr/?lat=41.051016...,0.000000,0.00000
...,...,...,...,...,...,...,...,...,...,...
68,152829,UTK,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),TRETUVAR - PARKE ÇALIŞMASI,2019-05-16,HAYIR,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,41.058968,29.01062
69,153422,ASFALT,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),ROBOT (YAMA),2019-05-21,EVET,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,41.058968,29.01062
70,154041,KORKULUK YAPIMI - ONARIMI,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),OTO KORKULUK,2019-05-26,EVET,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,41.058968,29.01062
71,154664,KORKULUK YAPIMI - ONARIMI,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),OTO KORKULUK,2019-05-29,EVET,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,41.058968,29.01062
72,155375,UTK,BEŞİKTAŞ,BARBAROS BULVARI(BALMUMCU MAH),TRETUVAR - PARKE ÇALIŞMASI,2019-06-10,HAYIR,http://sehirharitasi.ibb.gov.tr/?lat=41.058967...,41.058968,29.01062